1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 

In [2]:
import numpy as np

In [3]:
array = np.random.rand(2,3,5)
array = np.round(array,decimals = 1) 
array 

array([[[0.8, 0.7, 0.4, 0.1, 0.1],
        [0.2, 0.2, 0.6, 0.9, 0.9],
        [0.5, 0.7, 0.3, 0.1, 0.6]],

       [[0.7, 0.6, 0.2, 0.5, 0.2],
        [0.5, 0.3, 0.7, 0.3, 0.1],
        [0.2, 0.9, 0.8, 0.2, 0.4]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
array_media = np.mean(array).round(decimals = 1)
array_media

0.5

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
array_max = np.max(array).round(decimals = 1)
array_max

0.9

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
array_min = np.min(array).round(decimals = 1)
array_min

0.1

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [7]:
array_vacio = np.empty_like(array)
array_vacio

array([[[0.8, 0.7, 0.4, 0.1, 0.1],
        [0.2, 0.2, 0.6, 0.9, 0.9],
        [0.5, 0.7, 0.3, 0.1, 0.6]],

       [[0.7, 0.6, 0.2, 0.5, 0.2],
        [0.5, 0.3, 0.7, 0.3, 0.1],
        [0.2, 0.9, 0.8, 0.2, 0.4]]])

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [8]:
array

array([[[0.8, 0.7, 0.4, 0.1, 0.1],
        [0.2, 0.2, 0.6, 0.9, 0.9],
        [0.5, 0.7, 0.3, 0.1, 0.6]],

       [[0.7, 0.6, 0.2, 0.5, 0.2],
        [0.5, 0.3, 0.7, 0.3, 0.1],
        [0.2, 0.9, 0.8, 0.2, 0.4]]])

In [9]:
array_vacio = array_vacio.astype(str) # convertimos los valores en string

In [20]:
for arr  in range(array_vacio.shape[0]):  # sacar índice del eje 0 o array
    for fila  in range(array_vacio.shape[1]): # sacar índice del eje 1 o filas
        for columna  in range(array_vacio.shape[2]): # sacar índice del eje 1 o columnas
            if array[arr, fila, columna] == array_media: # creamos la condición y sustituye según los índices 
                array_vacio[arr, fila, columna] = 'A'
            if array[arr, fila, columna] > array_media:
                array_vacio[arr, fila, columna] = 'B'
            if array[arr, fila, columna] < array_media:
                array_vacio[arr, fila, columna] = 'C'
            if array[arr, fila, columna] == array_max:
                array_vacio[arr, fila, columna] = 'D'
            if array[arr, fila, columna] == array_min:
                array_vacio[arr, fila, columna] = 'E'
            

In [21]:
print(array_vacio)

[[['B' 'B' 'C' 'E' 'E']
  ['C' 'C' 'B' 'D' 'D']
  ['A' 'B' 'C' 'E' 'B']]

 [['B' 'B' 'C' 'A' 'C']
  ['A' 'C' 'B' 'C' 'E']
  ['C' 'D' 'B' 'C' 'C']]]


6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

In [23]:
unidimensional=np.empty(30)
unidimensional

array([0.8, 0.7, 0.4, 0.1, 0.1, 0.2, 0.2, 0.6, 0.9, 0.9, 0.5, 0.7, 0.3,
       0.1, 0.6, 0.7, 0.6, 0.2, 0.5, 0.2, 0.5, 0.3, 0.7, 0.3, 0.1, 0.2,
       0.9, 0.8, 0.2, 0.4])