1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
import numpy as np

In [18]:
array1 =np.random.randint(1,100,(2))
array1


array([ 6, 91])

In [17]:
array2 =np.random.randint(1,100,(2,3))
array2 


array([[36, 56, 22],
       [73, 30, 30]])

In [20]:
array3 =np.random.randint(1,100,(2,3,5))
array3 

array([[[20, 46, 17, 66, 81],
        [67,  5, 56, 57, 84],
        [29, 44, 63, 67, 80]],

       [[85, 66, 78, 79, 98],
        [33, 44, 19,  1, 95],
        [ 2, 50, 23, 12, 72]]])

2.Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [22]:
print(array1.shape)
print(array1.size)
print(array1.ndim)
print(array1.dtype)

(2,)
2
1
int64


In [28]:
def propiedades(array):
    print(f'La forma es {array.shape}')
    print(f'El tamaño  es {array.size}')
    print(f'La dimensión  es {array.ndim}')
    print(f'El tipo  es {array.dtype}')



In [29]:
propiedades(array1)

La forma es (2,)
El tamaño  es 2
La dimensión  es 1
El tipo  es int64


In [30]:
propiedades(array2)

La forma es (2, 3)
El tamaño  es 6
La dimensión  es 2
El tipo  es int64


In [31]:
propiedades(array3)

La forma es (2, 3, 5)
El tamaño  es 30
La dimensión  es 3
El tipo  es int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [37]:
matriz_identidad1 = np.identity(3)
matriz_identidad1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [39]:
array4 = np.ones_like(array3)
array4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5.Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? 
¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

No se pueden sumar arrays de diferente forma 

In [41]:
array5 = np.ones_like(matriz_identidad1)
array5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.add(array5,matriz_identidad1)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [43]:
np.multiply(array5,matriz_identidad1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.divide(matriz_identidad1,array5,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])