1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [3]:
import numpy as np

In [4]:
array1 =np.random.randint(1,100,(2))
array1


array([15, 52])

In [5]:
array2 =np.random.randint(1,100,(2,3))
array2 


array([[81, 62,  3],
       [23, 40, 53]])

In [6]:
array3 =np.random.randint(1,100,(2,3,5))
array3 

array([[[20, 41, 35, 34, 18],
        [49, 95, 32, 38, 11],
        [10, 42, 85, 19, 68]],

       [[17, 25, 30, 66,  1],
        [97, 70, 25, 58,  5],
        [61, 20, 90, 32, 29]]])

2.Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [28]:
def propiedades(array): # Una forma de hacerlo con print
    print(f'La forma es {array.shape}')
    print(f'El tamaño  es {array.size}')
    print(f'La dimensión  es {array.ndim}')
    print(f'El tipo  es {array.dtype}')



In [25]:
def propiedades2(array):#Otra forma de hacerlo con return 
    return f"""La forma es {array.shape},
        el tamaño  es {array.size},
        la dimensión  es {array.ndim} y 
        el tipo  es {array.dtype}"""
    
   



In [26]:
print(propiedades2(array1))

La forma es (2,),
        el tamaño  es 2,
        la dimensión  es 1 y 
        el tipo  es int64


In [29]:
propiedades(array2)

La forma es (2, 3)
El tamaño  es 6
La dimensión  es 2
El tipo  es int64


In [30]:
propiedades(array3)

La forma es (2, 3, 5)
El tamaño  es 30
La dimensión  es 3
El tipo  es int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [12]:
matriz_identidad1 = np.identity(3) # creado con método identity
matriz_identidad1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [13]:
array4 = np.ones_like(array3) # método ones_like e indicamos en nombre de la matriz array 3, que es de la que queremos copiar
array4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5.Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? 
¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [31]:
#No se pueden sumar arrays de diferente forma 
np.add(array2,matriz_identidad1)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [32]:
# creamos una matriz de al misma forma que la matriz identidad
array5 = np.ones_like(matriz_identidad1)
array5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# sumamos con método add
np.add(array5,matriz_identidad1)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [16]:
# multiplicamos 
np.multiply(array5,matriz_identidad1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# dividimos 
np.divide(matriz_identidad1,array5,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])