1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.

📌 Nota:
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
# Importamos la librería
import numpy as np 

In [2]:
# Array de 1 dimensión
array1 = np.random.randint(1,100,(2))
array1

array([34, 23])

In [3]:
# Array de 2 dimensiones (2 filas y 3 columnas)
array2 = np.random.randint(1,100,(2,3))
array2 

array([[25, 98,  1],
       [80, 85, 30]])

In [4]:
# Array de 3 dimensiones (2 matrices, 3 filas y 5 columnas)
array3 = np.random.randint(1,100,(2,3,5))
array3 

array([[[74, 73, 49, 95, 37],
        [24, 84, 78, 37, 17],
        [95, 31, 71, 60, 93]],

       [[64, 94, 85, 94, 43],
        [24,  4, 56, 59, 67],
        [55, 12,  4,  1, 26]]])

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [18]:
def propiedades(array): # Definimos la función de propiedades que toma como parametro el array y printea las propiedades de forma, tamaño, dimensión y tipo
    print(f'La forma es {array.shape}')
    print(f'El tamaño es {array.size}')
    print(f'La dimensión es {array.ndim}')
    print(f'El tipo es {array.dtype}')


In [22]:
def propiedades2(array):# Otra forma de hacerlo con un return de todas las propiedades seguidas
    return f"La forma es {array.shape}, el tamaño es {array.size}, la dimensión es {array.ndim} y el tipo es {array.dtype}"


In [23]:
propiedades2(array1)

'La forma es (2,), el tamaño es 2, la dimensión es 1 y el tipo es int64'

In [24]:
propiedades(array2)

La forma es (2, 3)
El tamaño es 6
La dimensión es 2
El tipo es int64


In [25]:
propiedades2(array3)

'La forma es (2, 3, 5), el tamaño es 30, la dimensión es 3 y el tipo es int64'

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [26]:
# Creaamos la matriz con el con método identity
matriz_identidad1 = np.identity(3) 
matriz_identidad1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [13]:
# Creamos el array con método ones_like e indicamos en nombre de la matriz array3, que es de la que queremos copiar.
array4 = np.ones_like(array3) 
array4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? 
¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [27]:
#No se pueden sumar arrays de diferente forma 
np.add(array2,matriz_identidad1)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [28]:
# Creamos una matriz de unos de la misma forma que la matriz identidad
array5 = np.ones_like(matriz_identidad1)
array5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# Sumamos con método add
np.add(array5,matriz_identidad1)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [30]:
# Multiplicamos 
np.multiply(array5,matriz_identidad1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Dividimos 
np.divide(matriz_identidad1,array5,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])