1- Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.
- Los valores de la segunda fila y las dos primeras columnas.
- Extraed las filas pares (incluyendo la 0) y todas las columnas.
- Extraed los valores que sean mayores que 0.5.
- Extraed los valores menores que 0.2 o mayores que 0.5

In [2]:
import numpy as np

In [8]:
array1 = np.random.rand(5,3)
array1

array([[0.72598941, 0.25574266, 0.86083923],
       [0.60741004, 0.39023448, 0.86489443],
       [0.80912176, 0.35243652, 0.01767688],
       [0.63190625, 0.80938558, 0.29353284],
       [0.06265806, 0.08395311, 0.79260016]])

In [9]:
#primera fila y segunda columna
array1[1,2]

0.864894425368738

In [10]:
#Valores de la segunda fila y las dos primeras columnas
array1[2,0:2]

array([0.80912176, 0.35243652])

In [11]:
#Filas pares incluyendo 0 y todas las columnas
array1[::2,:]

array([[0.72598941, 0.25574266, 0.86083923],
       [0.80912176, 0.35243652, 0.01767688],
       [0.06265806, 0.08395311, 0.79260016]])

In [12]:
#valores mayores de 0,5
array1[array1>0.5]

array([0.72598941, 0.86083923, 0.60741004, 0.86489443, 0.80912176,
       0.63190625, 0.80938558, 0.79260016])

In [13]:
#Menores que 0,2 y mayores de 0,5
array1[(array1<0.2)|(array1>0.5)]

array([0.72598941, 0.86083923, 0.60741004, 0.86489443, 0.80912176,
       0.01767688, 0.63190625, 0.80938558, 0.06265806, 0.08395311,
       0.79260016])

2. Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas
- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
- Sumad los dos arrays. ¿Podéis? ¿Por qué?
- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
.reshape()
.transpose()
Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [14]:
array2 = np.random.rand(2,5,3)
array2

array([[[0.89910725, 0.21567346, 0.59070676],
        [0.47670578, 0.98825904, 0.40738843],
        [0.17290614, 0.92656038, 0.95776712],
        [0.29121816, 0.90192855, 0.90225724],
        [0.01667074, 0.6926711 , 0.8787426 ]],

       [[0.82157246, 0.62160637, 0.0097469 ],
        [0.80461866, 0.8160905 , 0.84901253],
        [0.13019506, 0.23469296, 0.10889256],
        [0.4050295 , 0.67189278, 0.84122413],
        [0.13425165, 0.25022977, 0.17717265]]])

In [15]:
array3 = np.random.rand(3,2,5)
array3

array([[[0.51906038, 0.65733061, 0.7949204 , 0.61257008, 0.20756802],
        [0.78822099, 0.03726344, 0.10284973, 0.04931721, 0.14711575]],

       [[0.69609733, 0.28132642, 0.75196181, 0.73383213, 0.01104129],
        [0.54428551, 0.15069956, 0.00595865, 0.43754652, 0.86312587]],

       [[0.28409949, 0.44881981, 0.0283984 , 0.3509521 , 0.31479651],
        [0.27564817, 0.5651774 , 0.26930321, 0.48805486, 0.58855814]]])

In [16]:
def propiedades(array): 
    print(f'La forma es {array.shape}')
    print(f'El tamaño  es {array.size}')
    print(f'La dimensión  es {array.ndim}')
    print(f'El tipo  es {array.dtype}')

In [17]:
propiedades(array2)

La forma es (2, 5, 3)
El tamaño  es 30
La dimensión  es 3
El tipo  es float64


In [18]:
propiedades (array3)

La forma es (3, 2, 5)
El tamaño  es 30
La dimensión  es 3
El tipo  es float64


In [20]:
array4 = np.add(array2,array3)
#No se puede porque no tienen la misma forma

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [22]:
array3_reshaped = np.reshape(array3, (2,5,3))
array3_reshaped

array([[[0.51906038, 0.65733061, 0.7949204 ],
        [0.61257008, 0.20756802, 0.78822099],
        [0.03726344, 0.10284973, 0.04931721],
        [0.14711575, 0.69609733, 0.28132642],
        [0.75196181, 0.73383213, 0.01104129]],

       [[0.54428551, 0.15069956, 0.00595865],
        [0.43754652, 0.86312587, 0.28409949],
        [0.44881981, 0.0283984 , 0.3509521 ],
        [0.31479651, 0.27564817, 0.5651774 ],
        [0.26930321, 0.48805486, 0.58855814]]])

In [24]:
array4 = np.add(array2,array3_reshaped)
array4

array([[[1.41816763, 0.87300407, 1.38562716],
        [1.08927587, 1.19582706, 1.19560942],
        [0.21016958, 1.0294101 , 1.00708433],
        [0.43833391, 1.59802588, 1.18358366],
        [0.76863255, 1.42650323, 0.88978389]],

       [[1.36585797, 0.77230593, 0.01570555],
        [1.24216519, 1.67921638, 1.13311202],
        [0.57901487, 0.26309136, 0.45984466],
        [0.71982601, 0.94754095, 1.40640153],
        [0.40355486, 0.73828462, 0.76573079]]])

In [27]:
array3_transposed = np.transpose(array3, (1,2,0)) # Cambiamos con transposed la posición 1 a la 0, la 2 a la 1 y la 0 a la 2.
array3_transposed

array([[[0.51906038, 0.69609733, 0.28409949],
        [0.65733061, 0.28132642, 0.44881981],
        [0.7949204 , 0.75196181, 0.0283984 ],
        [0.61257008, 0.73383213, 0.3509521 ],
        [0.20756802, 0.01104129, 0.31479651]],

       [[0.78822099, 0.54428551, 0.27564817],
        [0.03726344, 0.15069956, 0.5651774 ],
        [0.10284973, 0.00595865, 0.26930321],
        [0.04931721, 0.43754652, 0.48805486],
        [0.14711575, 0.86312587, 0.58855814]]])

In [28]:
array5 = np.add(array2,array3_transposed)
array5

array([[[1.41816763, 0.91177079, 0.87480625],
        [1.13403639, 1.26958545, 0.85620824],
        [0.96782655, 1.67852218, 0.98616553],
        [0.90378824, 1.63576068, 1.25320935],
        [0.22423876, 0.70371238, 1.19353911]],

       [[1.60979345, 1.16589188, 0.28539507],
        [0.8418821 , 0.96679007, 1.41418993],
        [0.23304478, 0.24065162, 0.37819578],
        [0.45434671, 1.1094393 , 1.32927898],
        [0.28136739, 1.11335564, 0.76573079]]])