In [1]:
import numpy as np

1- ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [5]:
#Utilizando random.seed
np.random.seed(1)
arr1=np.random.rand(5,2)
arr1

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

In [6]:
np.random.seed(1)
arr2=np.random.rand(5,2)
arr2

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

2- Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [26]:
array_1 = np.random.uniform(size=(2,3,5), low = 0, high =10).astype(int)
print (array_1)
print ('-----------------------------------')
array_1_unique = np.unique(array_1)
print(array_1_unique)

[[[9 8 0 7 4]
  [9 2 2 0 4]
  [1 6 8 6 7]]

 [[3 8 4 8 6]
  [1 0 0 0 4]
  [1 0 7 3 7]]]
-----------------------------------
[0 1 2 3 4 6 7 8 9]


In [28]:
array_2 = np.random.binomial(10, 0.3, size=(2,3,5))
print (array_2)
print ('-----------------------------------')
array_2_unique = np.unique(array_2)
print(array_2_unique)

[[[1 4 1 2 4]
  [2 6 2 3 2]
  [5 2 3 3 5]]

 [[1 4 5 0 3]
  [2 5 3 4 3]
  [3 2 0 3 2]]]
-----------------------------------
[0 1 2 3 4 5 6]


3- En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?


In [29]:
#Elementos comunes:
np.intersect1d(array_1,array_2)
#Los elementos que están en ambos arrays los extraemos con intersect1d, estos números están en ambos arrays y lo devuelve como un array ordenado y en valores únicos.
#Como en array1 tenemos todos los números del 0 al 9 y en el array2 del 0 al 5, los elementos comunes son del 0 al 5.


array([0, 1, 2, 3, 4, 6])

In [30]:
#Unión de los dos arrays
np.union1d(array_1,array_2)
#Devuelve un array ordenado con valores únicos de los tomando los números que están tanto en un array como en otro.
#Al unir ambos arrays, como los valores del array2 están contenidos en el array1 la unión de ambos son los números unicos del array1.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#Elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial
np.setdiff1d(array_1,array_2_unique)
# Devuelve los elementos que se encuentran en el array1 y no se encuentran en los únicos del array2
# La diferencia entra ambos son los números que no están en el array2, es decir del 6 al 9.

array([7, 8, 9])

4- Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2. 
- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.
- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.
- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.
- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [33]:
array1 = np.random.randint(1,100,(80))
print(array1)
print ('-------------------------------')
array2 = np.random.randint(1,100,(80))
print(array2)

[69 55 26 84 28 57 93  9 56 77 47 50 12  9 62 75 24 89 90 83 83  6 43 47
 22 52 74 43 14 19 24 46 96 53 34 55 15 58 62 41 73 66 23  3 87  2 73 52
 72 88 78 63 49  1 43 40  4 58 44 54 44 75 99 98 76 60 67 75 92  6 27 68
 32 12  4 55  2 14 60 57]
-------------------------------
[82  9 39  5 71 77 74  6 80 85 60 32 91  8 67 33 47 76 83 45 65 38 48 74
 91 85 16 66 53 70 67 90 29 20 18  6 80 11 30 18 82 47  8 18 87 62 65  8
 30 56 29 44 99 56  6 51 93 64 53 35 99 84 78 38 90 55  5 44 12 30 77 90
 33 51 52 43 24 90 44 89]


In [34]:
#Valores únicos
array1= np.unique(array1)
print(array1)
print ('-------------------------------')
array2= np.unique(array2)
print(array2)

[ 1  2  3  4  6  9 12 14 15 19 22 23 24 26 27 28 32 34 40 41 43 44 46 47
 49 50 52 53 54 55 56 57 58 60 62 63 66 67 68 69 72 73 74 75 76 77 78 83
 84 87 88 89 90 92 93 96 98 99]
-------------------------------
[ 5  6  8  9 11 12 16 18 20 24 29 30 32 33 35 38 39 43 44 45 47 48 51 52
 53 55 56 60 62 64 65 66 67 70 71 74 76 77 78 80 82 83 84 85 87 89 90 91
 93 99]


In [35]:
# Diferencia del array1 y el array2
array3 = np.setdiff1d(array1,array2)
array3

array([ 1,  2,  3,  4, 14, 15, 19, 22, 23, 26, 27, 28, 34, 40, 41, 46, 49,
       50, 54, 57, 58, 63, 68, 69, 72, 73, 75, 88, 92, 96, 98])

In [36]:
# Diferencia del array2 y el array1
array4 = np.setdiff1d(array2,array1)
array4

array([ 5,  8, 11, 16, 18, 20, 29, 30, 33, 35, 38, 39, 45, 48, 51, 64, 65,
       70, 71, 80, 82, 85, 91])

In [37]:
# Union de los 2
array5 =np.union1d(array1,array2)
array5

array([ 1,  2,  3,  4,  5,  6,  8,  9, 11, 12, 14, 15, 16, 18, 19, 20, 22,
       23, 24, 26, 27, 28, 29, 30, 32, 33, 34, 35, 38, 39, 40, 41, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 82,
       83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 96, 98, 99])

In [38]:
# Valores únicos del 1
len(array1)

58

In [39]:
# Valores únicos del 2
len(array2)

50

In [40]:
#Diferentes, los que están en el 1 pero no en el 2
len(array3)

31

In [41]:
#Diferentes, los que están en el 2 pero no en el 1
len(array4)

23

In [42]:
# Union de ambos
len(array5)

81

In [44]:
# La len o size del array1 más lo que está en el array2 pero no en el array1 es igual a la len o size de la unión de ambos
len(array1) + len(array4) == len(array5)

True

In [45]:
# La len o size del array2 más lo que está en el array1 pero no en el array2 es igual a la len o size de la unión de ambos
len(array2) + len(array3) == len(array5)

True

Con los métodos de union y diferencia entre arrays como solo devuelve valores únicos es como utilizar operaciones matemáticas:
- setdiff1d: resta los arrays teniendo en cuenta el orden de los factores
- union1d: suma los arrays

Lo podemos ver en que la longitud del union se corresponde con la suma de la len del array1 y de la len de la diferencia del array2 con el array1, y con las len del array2 y de la diferencia de la len del 1 con el 2.
