1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 

In [1]:
import numpy as np

In [2]:
array = np.random.rand(2,3,5)
array = np.round(array,decimals = 1) #Usamos .round para redondear los decimales del array random a 1 decimal
array 

array([[[0.6, 0.8, 0.4, 0.6, 0.4],
        [0.2, 0.3, 0.6, 0.2, 0.5],
        [0.8, 0.6, 0.9, 0.4, 0.3]],

       [[0.1, 0.4, 0.6, 0.1, 0.4],
        [0.6, 0.2, 0.1, 0.3, 0. ],
        [0. , 0.4, 0.8, 0.1, 0.6]]])

2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [3]:
array_media = np.mean(array).round(decimals = 1)
array_media

0.4

3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
array_max = np.max(array).round(decimals = 1)
array_max

0.9

4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
array_min = np.min(array).round(decimals = 1)
array_min

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [6]:
#Creamos un array vacio con el metodo empty_like
array_vacio = np.empty_like(array)
array_vacio

array([[[0.6, 0.8, 0.4, 0.6, 0.4],
        [0.2, 0.3, 0.6, 0.2, 0.5],
        [0.8, 0.6, 0.9, 0.4, 0.3]],

       [[0.1, 0.4, 0.6, 0.1, 0.4],
        [0.6, 0.2, 0.1, 0.3, 0. ],
        [0. , 0.4, 0.8, 0.1, 0.6]]])

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [7]:
array_vacio = array_vacio.astype(str) # convertimos los valores en string

In [8]:
#Creamos un for loop en el que iteramos por todos los indices del array haciendo las modificaciones indicadas
for arr  in range(array_vacio.shape[0]):  # Sacar índice del eje 0 o array
    for fila  in range(array_vacio.shape[1]): # Sacar índice del eje 1 o filas
        for columna  in range(array_vacio.shape[2]): # Sacar índice del eje 1 o columnas
            if array[arr, fila, columna] == array_media: # Creamos la condición y sustituye según los índices 
                array_vacio[arr, fila, columna] = 'A'
            if array[arr, fila, columna] > array_media:
                array_vacio[arr, fila, columna] = 'B'
            if array[arr, fila, columna] < array_media:
                array_vacio[arr, fila, columna] = 'C'
            if array[arr, fila, columna] == array_max:
                array_vacio[arr, fila, columna] = 'D'
            if array[arr, fila, columna] == array_min:
                array_vacio[arr, fila, columna] = 'E'
            

In [9]:
print(array_vacio)

[[['B' 'B' 'A' 'B' 'A']
  ['C' 'C' 'B' 'C' 'B']
  ['B' 'B' 'D' 'A' 'C']]

 [['C' 'A' 'B' 'C' 'A']
  ['B' 'C' 'C' 'C' 'E']
  ['E' 'A' 'B' 'C' 'B']]]


6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [10]:
unidimensional=np.empty(30)
unidimensional

array([0.6, 0.8, 0.4, 0.6, 0.4, 0.2, 0.3, 0.6, 0.2, 0.5, 0.8, 0.6, 0.9,
       0.4, 0.3, 0.1, 0.4, 0.6, 0.1, 0.4, 0.6, 0.2, 0.1, 0.3, 0. , 0. ,
       0.4, 0.8, 0.1, 0.6])

In [13]:
array_30 = np.reshape(array_vacio,(30)) #Cambiamos la forma al array_vacío a uno unidimensional de 30, igual que el anterior
array_30

array(['D', 'B', 'D', 'C', 'C', 'B', 'B', 'E', 'C', 'B', 'C', 'B', 'C',
       'E', 'B', 'B', 'E', 'B', 'C', 'B', 'C', 'B', 'E', 'A', 'C', 'B',
       'B', 'C', 'B', 'C'], dtype='<U32')

In [14]:
for i in range(len(array_30)): # Iteramos por los indices del array30 (por los números en el rango de 0 a la longitud del array)
    if array_30[i] =='A' or  array_30[i] == 'B': # Creamos las condiciones para que para cada indice sustituya las letras por los números indicados.
        unidimensional[i] = 1
    if array_30[i] =='C' or array_30[i] =='D':
        unidimensional[i] = 2
    if array_30[i] =='E' :
        unidimensional[i] = 3

In [15]:
unidimensional

array([2., 1., 2., 2., 2., 1., 1., 3., 2., 1., 2., 1., 2., 3., 1., 1., 3.,
       1., 2., 1., 2., 1., 3., 1., 2., 1., 1., 2., 1., 2.])

Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [16]:
# Cambiamos la forma del array a la forma original, tridimensional con el metodo reshape
array_final = np.reshape(unidimensional,(2,3,5)) 
array_final

array([[[2., 1., 2., 2., 2.],
        [1., 1., 3., 2., 1.],
        [2., 1., 2., 3., 1.]],

       [[1., 3., 1., 2., 1.],
        [2., 1., 3., 1., 2.],
        [1., 1., 2., 1., 2.]]])